language: python

python:
  - 3.7

services:
  - redis-server
  - mysql
env:
  - DJANGO_VERSION=3.0.5

before_install:
    - sudo mysql -e 'CREATE DATABASE dailyfresh;'
    - python -m pip install -U pip

install:
    - pip install -r requirements.txt

script: True
