# Generated by Django 3.0.5 on 2020-04-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexgoodsbanner',
            options={'verbose_name': '主页轮播商品', 'verbose_name_plural': '主页轮播商品'},
        ),
    ]
